name: Spring Boot CI/CD

on:
  push:
    branches:
      - dev  # dev 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest  # Linux 가상 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 코드를 체크아웃

      - name: Set up JDK 11  # JDK 설정
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Deploy to EC2  # EC2 서버에 배포
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}  # GitHub Secrets에서 SSH 키 불러오기
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -i ~/.ssh/id_rsa ./build/libs/demo-0.0.1-SNAPSHOT.jar ec2-user@3.36.70.225:/home/ec2-user/
          ssh -i ~/.ssh/id_rsa ec2-user@3.36.70.225 "nohup java -jar /home/ec2-user/demo-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &"
